openapi: "3.0.0"
info:
  version: 1.0.0
  title: sushiApi
  description: Sushi API
paths:
  /sushi:
    get:
      description: sushiを複数取得
      operationId: findSushis
      parameters:
        - name: asc
          in: query
          description: 昇順にするかどうか
          required: false
          schema:
            type: boolean
        - name: limit
          in: query
          description: 取得する件数
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: sushi response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sushi"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: sushiの新規作成
      operationId: addSushi
      requestBody:
        description: 追加するsushi
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewSushi"
      responses:
        "200":
          description: sushi response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sushi"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /sushi/{id}:
    get:
      description: sushiをidを指定して取得
      operationId: findSushiById
      parameters:
        - name: id
          in: path
          description: 取得したいデータのid
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: sushi response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sushi"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Sushi:
      allOf:
        - $ref: "#/components/schemas/NewSushi"
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
    NewSushi:
      type: object
      required:
        - name
        - price
        - sozai
      properties:
        name:
          type: string
        price:
          type: integer
        sozai:
          type: array
          items:
            type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
