// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"sushiApi/internal/db/repository"
	"sushiApi/internal/http"
	"sushiApi/internal/usecase"
)

// Injectors from wire.go:

func InitServer() *api.Server {
	baseRepository := repository.NewBaseRepository()
	sushiData := repository.NewSushiData(baseRepository)
	sushi := usecase.NewSushi(sushiData)
	apiApi := api.NewApi(sushi)
	server := api.NewServer(apiApi)
	return server
}

// wire.go:

var repositories = wire.NewSet(repository.NewSushiData)

var usecases = wire.NewSet(usecase.NewSushi)
