// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"sushiApi/internal/db/repository"
	api "sushiApi/internal/http"
	"sushiApi/internal/usecase"

	"github.com/google/wire"
)

// Injectors from wire.go:

func InitServer() *api.Server {
	baseRepository := repository.NewBaseRepository()
	sushiDataInterface := repository.NewSushiData(baseRepository)
	sushi := usecase.NewSushi(sushiDataInterface)
	apiApi := api.NewApi(sushi)
	server := api.NewServer(apiApi)
	return server
}

// mock作るときはこれを使う
func InitMockServer() *api.Server {
	sushiDataInterface := repository.NewMockSushiData()
	sushi := usecase.NewSushi(sushiDataInterface)
	apiApi := api.NewApi(sushi)
	server := api.NewServer(apiApi)
	return server
}

// wire.go:

var repositories = wire.NewSet(repository.NewSushiData)

var usecases = wire.NewSet(usecase.NewSushi)

var mockRepositories = wire.NewSet(repository.NewMockSushiData)
